ADD: ATLAS Topics
SiLab-Bonn/silab-bonn.github.io pull request #15
Opened 2022-04-12 11:51 UTC by Marrkson

This MR adds Bachelor & Master topics in association with ATLAS

2022-04-12 12:26 UTC, leloup314 commented
Nice, will there be a separate PR for the introduction to ATLAS? ;)

2022-04-12 12:49 UTC, leloup314 requested changes

2022-04-12 12:49 UTC, leloup314 commented on topics/atlas.md
> +(_Last modified on_: {{ "2019-10-10 00:00:00 +0000" | date: '%B %d, %Y' }})
Correct date

2022-04-12 12:49 UTC, leloup314 commented on topics/atlas.md
> +(_Last modified on_: {{ "2019-10-10 00:00:00 +0000" | date: '%B %d, %Y' }})
Correct date

2022-04-13 09:47 UTC, Marrkson commented
Done.

2022-04-14 09:29 UTC, leloup314 approved these changes
Cool and good

2022-04-14 09:29 UTC, merged